# Generated by Django 4.2.3 on 2024-01-05 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionProduit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='produitPanier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='statistique',
            name='niveaux_stock',
        ),
        migrations.RemoveField(
            model_name='statistique',
            name='transactions',
        ),
        migrations.RenameField(
            model_name='produit',
            old_name='quantite',
            new_name='quantite_produit',
        ),
        migrations.RemoveField(
            model_name='panier',
            name='quantite',
        ),
        migrations.AddField(
            model_name='panier',
            name='quantite_achat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='produit',
            name='prix',
            field=models.FloatField(default=0.0),
        ),
        migrations.RemoveField(
            model_name='panier',
            name='produit',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='panier',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestionProduit.panier'),
        ),
        migrations.DeleteModel(
            name='Inventaire',
        ),
        migrations.DeleteModel(
            name='Statistique',
        ),
        migrations.AddField(
            model_name='produitpanier',
            name='panierAssocier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionProduit.panier'),
        ),
        migrations.AddField(
            model_name='produitpanier',
            name='produitAssocier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionProduit.produit'),
        ),
        migrations.AddField(
            model_name='panier',
            name='produit',
            field=models.ManyToManyField(through='gestionProduit.produitPanier', to='gestionProduit.produit'),
        ),
    ]
