# Generated by Django 4.2.3 on 2024-01-10 02:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestionProduit', '0006_panier_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='panier',
            name='date_panier',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='panier',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
