# Generated by Django 4.2.3 on 2024-01-10 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionProduit', '0007_panier_date_panier_alter_panier_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='produitpanier',
            name='quantite_achat',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
