# Generated by Django 4.2.3 on 2024-01-10 02:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestionProduit', '0008_produitpanier_quantite_achat'),
    ]

    operations = [
        migrations.AddField(
            model_name='produitpanier',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
