# Generated by Django 4.2.3 on 2024-01-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionProduit', '0009_produitpanier_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='panier',
            old_name='produit',
            new_name='produits',
        ),
        migrations.RenameField(
            model_name='produit',
            old_name='quantite_produit',
            new_name='quantite_achat',
        ),
        migrations.RemoveField(
            model_name='panier',
            name='date_panier',
        ),
        migrations.RemoveField(
            model_name='panier',
            name='quantite_achat',
        ),
        migrations.AddField(
            model_name='produit',
            name='creer_a',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='est_vendu',
            field=models.BooleanField(default=False),
        ),
    ]
