# Generated by Django 5.0.1 on 2024-01-12 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionProduit', '0011_rename_quantite_achat_produit_quantite_produit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='est_vendu',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
