# Generated by Django 5.0.1 on 2024-01-13 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionProduit', '0013_alter_produit_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='panier',
            old_name='produits',
            new_name='produit',
        ),
        migrations.AlterField(
            model_name='produit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='produit_images'),
        ),
    ]
