# Generated by Django 5.0.1 on 2024-01-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionProduit', '0015_rename_produit_panier_produits'),
    ]

    operations = [
        migrations.AddField(
            model_name='panier',
            name='quantite',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
